### ISSUE TITLE
OAT compatibility with TPM 2.0

### ISSUE THREAD

**Issue by nelsonspbr** [OpenAttestation/OpenAttestation#14]
Hi,

I would like to know if OpenAttestation is compatible with TPM 2.0. The documentation [1] says "in OAT 2.x, we will add geo-tagging support and TPM 2.0 support to enable upgraded TXT features for Grantley", but looking in the release notes [2-4] I have not found any references to this matter.

Or, similarly, is it possible to acquire TPM 2.0 enabled hardware but use OpenAttestation, even without TPM 2.0 new features?

Thank you,
Nelson

[1] https://01.org/openattestation/documentation/introduction-oat
[2] https://01.org/openattestation/downloads/2013/v2.1-source-code
[3] https://01.org/openattestation/downloads/2013/oat2.0-trust-agent-insides
[4] https://01.org/openattestation/downloads/2013/v2.0-source-code

**Comment by theopolis** [comment]
Hey @gwei3, it looks like 2.1, 2.2, 2.3 do not include TPM2.0 support. I see the TPM2.0-TSS project is coming along nicely, is there a roadmap you can share that maps TPM2 support to an expected version or date for support within OAT?

**Comment by gwei3** [comment]
Hi, Teddy, maybe @ZahediAquino can answer your question. :-)

**Comment by ZahediAquino** [comment]
@theopolis & nelsonspbr, it's in our plans but we don't have a date yet on when that will happen. To confirm, 2.1, 2.2 & 2.3 only support TPM 1.2. We will make an announcement as soon as we have a defined roadmap. Thanks

**Comment by ZahediAquino** [comment]
Support for TPM 2.0 will come in 1st Half of 2017. It will be provided through the Open CIT project. https://github.com/opencit/opencit
