### ISSUE TITLE
GetEK step in the control flow in overview.pdf

### ISSUE THREAD

**Issue by baaltommysu** [OpenAttestation/OpenAttestation#27]
Hi, I am reading the overview description of OpenAttestation version 1.6, and the file below describing OAT version 2.0. 
https://github.com/OpenAttestation/OpenAttestation/blob/master/docs/Overview.pdf
https://01.org/sites/default/files/downloads/openattestation/oat2.0-trust-agent.pdf

I am confused in the initialisation phase to create AIK certificate for the attester. In both files, there is a step to get the EK from the TPM, and send it to the privacyCA. However, according to the TCG specifications, the EK and the SRK should never leave the TPM. 

May I ask if this is a misunderstanding or you actually get the EK out of the TPM? And how you can manage this?

Thank you very much!

**Comment by ZahediAquino** [comment]
EK private key never leaves them TPM.  

The protocol is referencing the EK public key.

**Comment by baaltommysu** [comment]
Thanks, good to know that.
