### ISSUE TITLE
OAT supprts TPM 2.0?

### ISSUE THREAD

**Issue by mipsan** [OpenAttestation/OpenAttestation#30]
Hi,

It might be very foolish question, I'd like to ask whether OAT supports TPM 2.0.
Documents in the project say only TPM 1.2 compliant devices.

If not, any plan to support in the future?

Thanks,

**Comment by ZahediAquino** [comment]
OAT currently supports TPM 1.2 only.

There is a plan to add support, but we don't have date defined.

**Comment by mipsan** [comment]
Appreciation !
