### ISSUE TITLE
retrieve only one host 

### ISSUE THREAD

**Issue by mipsan** [OpenAttestation/OpenAttestation#35]
TrustDashBoard shows all hosts added at a time.
How can I retrieve only one host user wants to know on the web browser of at command line.
User may pass its IP address through URL or manual input.

**Comment by ZahediAquino** [comment]
@mipsan, you can do so with either of the following...

URL in your browser:
http://YOURSERVERSIP:8080/AttestationService/resources/hosts/trust?hostName=YOURHOSTNAMEIP

Response should be something like:
{
hostname: "YOURHOSTNAMEIP",
trust: {
bios: false,
vmm: true,
location: false,
asset_tag: false
}
}


======================================================================
Command Line:
In the github project find the scripts in the CommandTool directory and run the following:

bash oat_pollhosts -h YOURSERVERSIP '{"hosts":["YOURHOSTNAMEIP"]}'

Response should be:
{"hosts":[{"host_name":"YOURHOSTNAMEIP","trust_lvl":"untrusted","vtime":"2016-01-06T22:26:31.492+0000"}]}

**Comment by mipsan** [comment]
Thanks,

The 1st thing works very well, however, the 2nd CLI approach returns wrong
answer as follow:
#bash oat_cert -h 172.25.0.169
connect: Connection refused
connect: error=111

Then, oat_pollhosts returns nothing,
root@oat-client:/home/debian/scripts/OAT/CommandTool# bash oat_pollhosts -h
172.16.195.114 '{"hosts":["172.25.0.169"]}'
 '{"hosts":["172.25.0.169"]}'

what should I check for it?

**Comment by ZahediAquino** [comment]
I would check to see if the ssl port is open... or maybe a firewall issue?

**Comment by mipsan** [comment]
Zahedi, 

You're right. The problem was occurred by Port no.
CommandTool package uses different port no. to OAT package's port no.

Thanks a lot!!
