### ISSUE TITLE
not sync between CommandTool and Web Attestation service

### ISSUE THREAD

**Issue by mipsan** [OpenAttestation/OpenAttestation#36]
Hi,

oat_pollhosts and Attestation service on the web return different result.
Should I refresh something for up-to-date info?

1. CommandTool
# bash oat_pollhosts -h 192.168.2.182 '{"hosts":["192.168.2.183"]}'
{"hosts":[{"host_name":"192.168.2.183","trust_lvl":"untrusted","vtime":"2016-01-14T12:20:50.679+0000"}]}

2. Web access
http://192.168.2.182:8080/AttestationService/resources/hosts/trust?hostName=192.168.2.183
{"hostname":"192.168.2.183","trust":{"bios":true,"vmm":false,"location":false}}

Web-access shows the client is 'trust'.
At the time, trustdashboard shows as follow:

![txt-shot](https://cloud.githubusercontent.com/assets/3205851/12324423/c60e897c-bb05-11e5-9151-b5bfff58e5f4.png)

**Comment by ZahediAquino** [comment]
The information seems correct, Web-Access gives you more detailed information, but they both say the same thing.

A host is only trusted if all of the components in the Chain of Trust are trusted (Bios, VMM, location), in this case CommandTool is telling you is "untrested", if you look at the trustdashboard you can see why, only 1 of the 3 components in the chain of trust are trusted (which means the host is "untrusted").

Does this make sense?

**Comment by mipsan** [comment]
Thanks Zahedi,
You always help my question.

I understood what you say.

The client is untrusted now, as 1)CommandTool and 3)TrustDashBoard say. 
But 2)web-access says TRUST, and it shows VMM and location are FALSE in detailed info.   As you say, all of the parts should be trusted, I think it should be untrusted.

**Comment by ZahediAquino** [comment]
Can you paste a better screenshot of where 2)Web-Access says the host is Trusted? (show column names)

**Comment by mipsan** [comment]
Below screenshot shows as follow: 
{
"hostname": "192.168.2.183",
"trust": {
"bios": false,
"vmm": true,
"location": false}
}

![attest_scr](https://cloud.githubusercontent.com/assets/3205851/12375729/c90e38c8-bd14-11e5-8f66-a0ad6cee20fb.png)

And FYI, I attach another screenshot which includes 3 different accesses im a image:
web browser, web access query and command tool.

![attest_scr2](https://cloud.githubusercontent.com/assets/3205851/12375736/317bb7be-bd15-11e5-9445-123dd2f9a81a.png)

**Comment by ZahediAquino** [comment]
Ok, I see what you mean, but the information is still correct. You are getting back 2 properties in the 2)Web-Access (I'm going to rewrite it a bit so it's easier to understand), the 'hostname' parameter, which has the hosts IP and the 'trust' parameter which is an array with the different status values for bios, vmm and location.

     "hostname" = "192.168.2.183"                 <-- Host IP
     "trust" = [ "bios": false, "vmm": true, "location": false]      <--- Array with the status for 3 components

'trust' is the parameter, it does not tell you if the host is trusted or not... to know if the host is trusted or not, the portal looks at the 3 components (bios, vmm, location) and determines if the host is trusted or not... I think your confusion is with the name of the parameter 'trust'.

**Comment by mipsan** [comment]
Zahedi,

You're right!
I though the 'trust' as a status!
Thanks a lot!
