### ISSUE TITLE
trivial question

### ISSUE THREAD

**Issue by mipsan** [OpenAttestation/OpenAttestation#42]
'Location' at Trust Dash Board!
What does it mean?

**Comment by adolfovega** [comment]
Hi,

Could you please provide more details? In what part of the trust dashboard you get the "Location" text?

Thanks!

Adolfo,

**Comment by adolfovega** [comment]
Hello again,
If you are referring to previous versions of OAT this "Location" column is only a placeholder. Starting with OAT version 2.3 this column was renamed to "Asset tag". This allows you to create and provision Asset Tags for your hosts. Asset Tags are basically attributes you define to allow additional identifying controls.

For instance you can define location information tags (building, city, state, etc) or server type tags (prod, test, dev, etc) or any other user defined tags that make sense for your project.

Please let us know if this helps,

Thanks!

Adolfo,

**Comment by mipsan** [comment]
Hello Adolfo,

That's it what I ask!
Thanks a lot!

mipsan
