### ISSUE TITLE
Need delete v2.3 tag

### ISSUE THREAD

**Issue by gwei3** [OpenAttestation/OpenAttestation#44]
https://github.com/OpenAttestation/OpenAttestation/wiki/OAT-v2.3-Ubuntu-14.04 tell people to check out v2.3 code via "git checkout v2.3". This was intended to checkout v2.3 branch, but in fact the v2.3 tag will be checked out.

The v2.3 tag looks like an incorrect one for people who want to use v2.3 code. So I suggest to delete this tag and add tags with format v2.3.x later when needed to prevent from duplication with branch name.

**Comment by ZahediAquino** [comment]
Done
