### ISSUE TITLE
Not getting any hosts for TrustedFilter

### ISSUE THREAD

**Issue by schrotti12** [OpenAttestation/OpenAttestation#45]
I have configured nova.conf on the controller node with following settings.

**[DEFAULT]
compute_scheduler_driver=nova.scheduler.filter_scheduler.FilterScheduler
scheduler_available_filters=nova.scheduler.filters.all_filters
scheduler_default_filters=AvailabilityZoneFilter,RamFilter,ComputeFilter,TrustedFilter
[trusted_computing]
attestation_server = 10.0.1.5
attestation_port = 8181
attestation_server_ca_file = /etc/nova/certfile.cer
attestation_api_url = /AttestationService/resources
attestation_auth_blob = oatoat
auth_timeout = 60**

But it always says
`
INFO nova.filters [req-9c19b42e-880a-42da-b1f5-7e65c71ef9ee None] Filter TrustedFilter returned 0 hosts
`
in /var/log/nova/nova-scheduler.log when trying to launch a trusted instance.
But 
`curl --noproxy 10.0.1.5 -v --cacert /etc/nova/certfile.cer -H "Content-Type: application/json" -X POST -d '{"hosts":["compute1","compute2"]}' https://10.0.1.5:8181/AttestationService/resources/PollHosts`
tells me the following:
`{"hosts":[{"host_name":"compute1","trust_lvl":"trusted","vtime":"2016-02-29T22:29:26.365+0000"},{"host_name":"compute2","trust_lvl":"trusted","vtime":"2016-02-29T22:29:26.365+0000"}]}`

So I have to assume its a configuration error. I need help for my master thesis pretty urgent and would appreciate some help here.
On the two compute nodes there is no additional configuration.

Maybe I got the attestation_auth_blob value wrong to connect to the OAT server on 10.0.1.5 but I was not able to find a tutorial on how to generate a blob.

**Comment by adolfovega** [comment]
Hello,

Are you using OAT 2.3? OAT uses SAML to communicate with openstack but this functionality is available only in version 2.3.
If you are already using 2.3 then I guess the error you get might be because you are not using the correct endpoint.
Could you please try with the following configuration instead:

attestation_server = 10.0.1.5
attestation_port = 8080
attestation_server_ca_file = /etc/nova/certfile.cer
attestation_api_url = /AttestationService/resources/saml/assertions/host
attestation_auth_blob = oatoat


Please let us know if this helps,

Thanks!

Adolfo,

**Comment by adolfovega** [comment]
Hello again,

By the way, below is an example on how to make a call to the saml endpoint. I thought it might be helpful for you to verify if you can get the host info with this.
So if you use a tool like SoapUI or any other similar REST API tool it is something like this. 
URL:http://10.1.70.164:8080/AttestationService/resources/saml/assertions/host?hostName=oat-ubuntu1404-gdcclient.fm.intel.com&force_verify=false
Method: GET
Content-type: application/xml

Please note that "hostName" is a parameter, you will need to specify your own host name of course, :-)

Thanks!

Adolfo,

**Comment by schrotti12** [comment]
Hi, Thanks for the hints. I try to access the OAT service with SoapUI.
I am using version 2.2 on Ubuntu 14.04.4 because of maven build problems with 2.3.

**Comment by adolfovega** [comment]
Not really.

For Openstack communication we use SAML (an XML based format) not JSON.

This saml file contains detailed information about your hosts just like JSON, but in XML format. The endpoint to get the saml is:
/AttestationService/resources/saml/assertions/host

However this feature is available in version 2.3 only as I mentioned in a previous post. "PollHosts" is a JSON endpoint, it only retrieves host info but does not integrate with Openstack.

Not sure if this answers your question?

Adolfo,

**Comment by adolfovega** [comment]
A few corrections:
- version 2.2 does integrate with Openstack. The main difference with 2.3 is that a new saml endpoint is available to include asset tag info.
Let me investigate a bit more on what endpoint is being used for 2.2, it might probably be the "PollHosts" that you mentioned but I need to confirm that.

Thanks!

Adolfo,

**Comment by schrotti12** [comment]
Hello
Thanks for the answers. I tried changing the parameter
"attestation_api_url = /AttestationService/resources"
to
"attestation_api_url = /AttestationService/resources/saml/assertions/host"
but there are still no valid hosts found. I can launch regular instances but none with the trusted flag set.

Another question is: Do I have to change anything in the nova.conf file on the compute nodes. Until now I have only changed the nova.conf on the controller node. It is a nova network setup with 4 nodes: Controller, Network, Compute1, Compute2
All of these nodes are trusted and validated through OpenAttestation. I have followed the instructions on the official Juno-Documentation.

**Comment by adolfovega** [comment]
Hello,
Never mind, your nova.conf looks right. Can you change back your parameter to 
"attestation_api_url=/AttestationService/resources"....

Once you do that can you also check if  there is any https_proxy in your system? What do you get if you run the curl command without the "--noproxy" option?

**Comment by schrotti12** [comment]
Here is the full output of curl without the noproxy option
**
root@controller:~# curl 10.0.1.5 -v --cacert /etc/nova/certfile.cer -H "Content-Type: application/json" -X POST -d '{"hosts":["compute1","compute2"]}' https://10.0.1.5:8181/AttestationService/resources/PollHosts
* Rebuilt URL to: 10.0.1.5/
* Hostname was NOT found in DNS cache
*   Trying 10.0.1.5...
* connect to 10.0.1.5 port 80 failed: Verbindungsaufbau abgelehnt
* Failed to connect to 10.0.1.5 port 80: Verbindungsaufbau abgelehnt
* Closing connection 0
curl: (7) Failed to connect to 10.0.1.5 port 80: Verbindungsaufbau abgelehnt
* Hostname was NOT found in DNS cache
*   Trying 10.0.1.5...
* Connected to 10.0.1.5 (10.0.1.5) port 8181 (#1)
* successfully set certificate verify locations:
*   CAfile: /etc/nova/certfile.cer
  CApath: /etc/ssl/certs
* SSLv3, TLS handshake, Client hello (1):
* SSLv3, TLS handshake, Server hello (2):
* SSLv3, TLS handshake, CERT (11):
* SSLv3, TLS handshake, Server key exchange (12):
* SSLv3, TLS handshake, Request CERT (13):
* SSLv3, TLS handshake, Server finished (14):
* SSLv3, TLS handshake, CERT (11):
* SSLv3, TLS handshake, Client key exchange (16):
* SSLv3, TLS change cipher, Client hello (1):
* SSLv3, TLS handshake, Finished (20):
* SSLv3, TLS change cipher, Client hello (1):
* SSLv3, TLS handshake, Finished (20):
* SSL connection using DHE-RSA-AES256-SHA
* Server certificate:
*        subject: C=US; O=My Org; OU=Mt Wilson; CN=10.0.1.5
*        start date: 2016-02-15 09:12:31 GMT
*        expire date: 2026-02-12 09:12:31 GMT
*        subjectAltName: 10.0.1.5 matched
*        issuer: C=US; O=My Org; OU=Mt Wilson; CN=10.0.1.5
*        SSL certificate verify ok.
> POST /AttestationService/resources/PollHosts HTTP/1.1
> User-Agent: curl/7.35.0
> Host: 10.0.1.5:8181
> Accept: */*
> Content-Type: application/json
> Content-Length: 33
>
* upload completely sent off: 33 out of 33 bytes
< HTTP/1.1 200 OK
* Server Apache-Coyote/1.1 is not blacklisted
< Server: Apache-Coyote/1.1
< Content-Type: application/json
< Transfer-Encoding: chunked
< Date: Wed, 02 Mar 2016 19:35:19 GMT
<
* Connection #1 to host 10.0.1.5 left intact
{"hosts":[{"host_name":"compute1","trust_lvl":"trusted","vtime":"2016-03-02T19:35:13.190+0000"},{"host_name":"compute2","trust_lvl":"trusted","vtime":"2016-03-02T19:35:13.190+0000"}]}
**
Still get the Json response correctly.

**Comment by adolfovega** [comment]
Ok, looks like you have no proxy but could you please confirm?

echo $https_proxy 

Also check your bashrc for any https_proxy entry:

vi ~/.bashrc

**Comment by schrotti12** [comment]
No output for the commands "cat ~/.bashrc | grep http" or "cat ~/.bashrc | grep proxy" and "echo $https_proxy" did not return any output. And I don't remember setting up a proxy ;-)
Also the OAT-Server is reachable. Controller node only has one NIC interface:
`ping -I eth0 10.0.1.5
PING 10.0.1.5 (10.0.1.5) from 10.0.0.11 eth0: 56(84) bytes of data.
64 bytes from 10.0.1.5: icmp_seq=1 ttl=63 time=1.32 ms`

**Comment by adolfovega** [comment]
Umm, have you tried using a different value for the blob parameter? I am not sure if it will work, but I just checked a nova config file for version 2.3 and this uses no blob, as shown below:

attestation_auth_blob =

Also, you mentioned in a previous post that you are able to launch regular instances but none with the trusted flag set. Could you provide a screenshot? 

Thanks!

**Comment by schrotti12** [comment]
Thanks for the support, first of all!
When using a regular flavor like the following it works.
![regular](https://cloud.githubusercontent.com/assets/922195/13477666/c7c5339a-e0cd-11e5-8858-d77f9f896c96.jpg)
Message from OpenStack:
![spawning](https://cloud.githubusercontent.com/assets/922195/13477697/e3489c4c-e0cd-11e5-9f07-d9c78f05ddd2.jpg)
and in the list
![running](https://cloud.githubusercontent.com/assets/922195/13477701/e805683c-e0cd-11e5-8ac8-e5639c6a163d.jpg)
but when trying to create a trusted instance with the following config
![trusted](https://cloud.githubusercontent.com/assets/922195/13477718/f9c8daa4-e0cd-11e5-9a59-fe8fc3403992.jpg)
it says
![terminated](https://cloud.githubusercontent.com/assets/922195/13477723/ff668254-e0cd-11e5-97db-8ff8ed36d486.jpg)
with the log message mentioned above.

**Comment by adolfovega** [comment]
Thanks!
We might need to take a look at the log files.
Could you please send the following logs:

1. Openstack log: /var/log/nova/nova-scheduler.log
2. OAT server log: catalina.out
3. OAT agent log: /var/log/tagent.log

**Comment by schrotti12** [comment]
Oh my god, this is so embarrassing ...
It was a problem on the OAT-Server. The compute1 and compute2 hosts were defined statically in the file /etc/hosts but the domain, in my case "master", was missing. This caused OpenAttestation to not find the corresponding IP address because OpenStack requested the hostname with the domainname. That would be in my case "compute1.master" and in the hosts file was just "10.0.0.31 compute1". After I changed the line to "10.0.0.31 compute1 compute1.master" it worked.
Thank you so much for your help. Your request for the log files brought me on the right direction!
![firefox_2016-03-03_22-45-05](https://cloud.githubusercontent.com/assets/922195/13510611/a19be460-e191-11e5-93e3-d7790d21caf1.png)

**Comment by adolfovega** [comment]
Excellent! I am glad to know your issue has been solved. :-)
Thanks for sharing the solution, it might help anyone else facing the same issue in the future.

Have a nice day!

Regards!

Adolfo,
