### ISSUE TITLE
TPM clear at BIOS, and Add Host at Cloud Porta

### ISSUE THREAD

**Issue by mipsan** [OpenAttestation/OpenAttestation#46]
what I did is,
1) TrustBoot install and boot the board with Trusted boot.
    - as one of jobs,  tboot policy applied here
2) TPM clean at BIOS
3) install Open Attestation client.
4) Add host to Reference Cloud Portal of Attestation server.

Here, I wondered if **TPM clearing of 2) changes or clears tboot policy of 1).**

---------------------------
As test, I tried to change the order Tboot policy step at the next 3).
Then, I got the '1007 error code:  'Trust Agent: Error while creating identity.' [AS_TRUST_AGENT_ERROR] [1012]'
----------------------------
Thanks in advance,

**Comment by adolfovega** [comment]
Hello,

Yes, clearing TPM will clear ownership and also the tboot policy in NV index.
The suggested steps are as follows:

1) TrustBoot install and boot the board with Trusted boot.
2) Update OpenAttestation server side property files with the tpm owner password used in step 1)
3) Install Open Attestation client.
4) Add host to Reference Cloud Portal of Attestation server.

Hope it helps!

Thanks!

Adolfo,

**Comment by mipsan** [comment]
Thanks Adolfo,

If I use the same ownership PW and property, then can I do the steps; 2 - 3 - 1- 4 ?

**Comment by adolfovega** [comment]
The recommended sequence is 1-2-3-4.
Is there any special reason you want to do it  2-3-1-4 instead?

Thanks!

Adolfo,

**Comment by mipsan** [comment]
Adolfo,

I'm testing client side repeatedly, and installing OS many times.

Thanks,
mipsan

**Comment by adolfovega** [comment]
Oh ok... yes, it is possible to do it that way also.

Thanks!

Adolfo,

**Comment by mipsan** [comment]
Thanks,

When I configure OAT client as (2)-3-1-4, here 2 is pre-done, I always face with the same problem.

"Trust Agent failed with code '1007' and message 'Trust Agent: Error while creating identity.' [AS_TRUST_AGENT_ERROR] [1012]" 

And fail to add host.

(2)-3-4-1, it returns 0xc041661 TXT error code and reboots infinitely. 

mipsan

**Comment by mipsan** [comment]
This error, 0xC041661 was from my fault. 
I copied wrong list.data file to /boot.

mipsan
