### ISSUE TITLE
OAT on the TPM2.0 or ARM based embedded systems

### ISSUE THREAD

**Issue by mipsan** [OpenAttestation/OpenAttestation#47]
I read the previous issue OAT does not support TPM2.0. 
Any updates about it?

How about ARM based embedded systems which have a TPM chip.
I wonder whether OAT may run on these systems.

mipsan

**Comment by ZahediAquino** [comment]
We don't have a clear date for TPM 2.0 support yet. All efforts are moving now towards the Open CIT project. 

On ARM it won't work, besides the TPM chip, you need the Intel TXT Technology that comes with Intel processors.

**Comment by ZahediAquino** [comment]
Quick update, @mipsan TPM 2.0 support will come in 1st Half of 2017. Reopen if necessary.
