### ISSUE TITLE
How does asset tag work?

### ISSUE THREAD

**Issue by baaltommysu** [OpenAttestation/OpenAttestation#48]
Hi, 

I am reading the readme file in the repository. And I got confused how asset tag works in OAT v2.3. 

Please correct me if I understand something wrong. 

The asset tag management service will extend the administrator defined descriptors into the PCRs. What to be extended is configured in the OAT server, and they are called 'attribute'. They are received by the attesting platform and set by the asset tag management service to be extended into PCRs. Each attribute has a name/value pair. 
Then the step 'certificate creation', who will create the certificate and what is that for? And why to extend the SHA1 of the certificate pairs (the pairs mean the private and the public parts of one certificate or one certificate for the attribute name and another one for the attribute value?). In the last step of tag attestation, what does it mean the actual certificate?

I am sorry if I have too many questions, only one more, may I ask if you have a more detailed documentation of how asset tag (or OATv2.x) works?

Thank you very much and best wishes!
Tao

**Comment by adolfovega** [comment]
Hello,

Asset Tagging is only available in version 2.3
You basically define your asset tags as an XML file. This XML file will contain all your descriptors. This provision method through an XML file is called "Pull provisioning"

Please check the below link for a detailed installation process for Ubuntu 14.04 including asset tagging:

https://github.com/OpenAttestation/OpenAttestation/wiki/OAT-v2.3-Ubuntu-14.04

For Redhat:

https://github.com/OpenAttestation/OpenAttestation/wiki/OAT-v2.3-RHEL-7.1

Hope it helps,

Thanks!

Adolfo,

**Comment by baaltommysu** [comment]
Hi Adolfo,

Thank you for your reply.

If asset tag is only available for OAT v2.3, may I ask the differences between OAT v1.7 and v2.0? Because I saw a lot code changed.

Regarding to the asset tags, what does it mean the certificate creation? Because I don't find related information in the link you sent.

Thank you so much and best wishes.
Tao

**Comment by adolfovega** [comment]
Hi Tao,

Previous versions before OAT v.2.3 provided host integrity attestation using tpm quotes. It was the first approach but unfortunately it didn't include asset tagging. This feature was recently added for v.2.3 as already mentioned.

The asset tag certificate is the certificate created with your asset tag info to be written to TPM. When you run the tpa.sh script on your client side it uses your XML file (asset tag info) and then attempts to communicate with your attestation server (OAT) and get a valid assettag certificate. This is used later on to deploy asset tag info into the TPM chip. 

The tpa script is part of the asset tag process and is documented under the "Asset Tag Client Installation" section in the same link I provided in the previous post.

Please let us know if this helps, 


Thanks!

Adolfo,

**Comment by baaltommysu** [comment]
Hi Adolfo, 

Thank you for your reply, it helps a lot. 

If I may ask another question, because right now I am deploy OAT1.7 in my server, it works fine, but I would like to know what are the differences between it to the later versions, like 2.0, 2.1 and 2.2. So I can choose one to upgrade. 

I promise I will close this issue after this question. :)

Thanks and best wishes!
Tao

**Comment by adolfovega** [comment]
Hi Tao,
These are the features for each version as published in 01.org/openattestation website

OAT v1.7:
- New file-based storage method for integrity reports
- PCR validation and Report comparison as external analysis
- Support to external analysis tools
- Include BIOS and IMA measurements into IR
- Scalability feature: client sends only measurements not already sent in a previous report
- Avoid duplicate reports
- Support for asynchronous (periodic or not) attestation requests
- Remove -sslv3 in CommandTool and define environment variable to identify the location of certificate


OAT v2.1:

- Support XenServer* specific Trust Agent
- Support EK Certificate stored in the file
- Consolidated TPM access code in NIARL module
- EC signing on PCA
- Both 20-character and 40-hex-digit owner password can be used for client provisioning
- Both hostname and IP address can be used to pollhost


OAT v2.2:

- Enhanced build process
- Install scripts to simplify deployment process
- Flexible length TPM password
- HA (High Availability) solutions
- Automatic test framework & test cases

Hope it helps!

Thanks!

Adolfo,

**Comment by baaltommysu** [comment]
Thank you very much Adolfo, this really helps a lot!

Best wishes!
Tao

**Comment by kgoldman** [comment]
Could you explain a bit more about the IMA measurements?

Are you just sending the IMA event log to the server for logging, 
validating the log against PCR 10, validating signatures, ...?

**Comment by adolfovega** [comment]
Hi Ken,

In OAT v1.7 Integrity Report (IR) format was different and I don’t have enough information since this release is no longer supported.

However the same idea applies in OAT 2.3... the client sends back the event log to the server for logging.
I have attached a couple sample files. The first one (client_request.txt) shows a sample response from the client that is sent back to the server for logging. As you can see the AIK certificate is part of the response along with the event log, both of them are sent in encrypted form.
The second sample file (event_log.txt) is the actual event log info (after being decrypted) and it shows how it looks like and the type of information that is being sent.

Hope it helps!

Thanks!

Adolfo,
